### ISSUE TITLE
Is this repository mantained?

### ISSUE THREAD

**Issue by facconi** [facconi/sentry-redmine#6]
Is this repository mantained?
This plugin is not working with latest version of Redmine.
I can try to fix this, but I'd like to know if it is maintained prior to do this.
Thanks, Francesco

**Comment by aadis** [comment]
Hi,

Haven't maintained since we moved off redmine. Can handover to you.

**Comment by facconi** [comment]
Hi. Thank you. Do you prefere me to fork and send you pull requests so you can release on PyPI, or do you prefere to work in another way? Thanks, Francesco

**Comment by aadis** [comment]
I’d like to hand over the entire thing to you, including PyPi. I won’t be able to devote pretty much any time to it. How shall we do this? 

## Regards

Aaditya Sood
CEO, Idea Device
US: +1 (650) 784-0420
India: +91 98-451-00258
www.ideadevice.com | www.calm.io

**Comment by facconi** [comment]
Hi. It’s ok for me. I do not know if there is any way to “pass” PyPi permissions, I have to check.
Francesco

**Comment by facconi** [comment]
I am mantaining now the repository, I am developing some updates. News soon!

**Comment by meyer59** [comment]
Hi,
Is this repo still mantained ?

**Comment by facconi** [comment]
Hi @meyer59 , unfortunately this repo is no longer maintained.
Are you interested in holding it?

**Comment by meyer59** [comment]
Not yet. Thank you
